[sbc] Update to 1.4. JB#56373
There was also 1.5 with some SSE support, but that has some
compiler problem: undefined reference to `__builtin_cpu_init'

I'm good enough with 1.4 and the cleanups for now.

The licensing details were also slightly off.